version: "3.9"

services:
  bingo:
    container_name: bingo
    env_file:
      - .env
    expose:
      - "8000"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: bingo_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - bot
    restart: unless-stopped
